# @name get-prompts
GET https://upload-ai-1g12.onrender.com/prompts


###

# @name upload
POST https://upload-ai-1g12.onrender.com/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="audio.mp3"
Content-Type: audio/mpeg

< ./audio.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST https://upload-ai-1g12.onrender.com/videos/e9124653-6372-408b-aeb0-7dd87521cd6e/transcription
Content-Type: application/json

{
  "prompt": "Arte, no capricho"
}

###

# @name generate-ai-completion
POST https://upload-ai-1g12.onrender.com/ai/complete
Content-Type: application/json

{
  "videoId": "e9124653-6372-408b-aeb0-7dd87521cd6e",
  "temperature": 0.5,
  "prompt": "Gere um resumo sucinto da transcrição do vídeo informada a seguir: '''{transcription}'''"
}